### PR TITLE
improving test coverage

### PR DESCRIPTION
**Pull request by BooleanJulien**

### CODE REVIEW

**Review by zackt113 — APPROVED** [review]
LGTM!

**Comment by voremargot** [comment]
Hey! I added some updates to my function this morning (mainly changed the saving parameters like they are in python). @BooleanJulien and @zackt113 Can you give a quick look through of the changes I made? I hadn't realized this pull request was open so they ended up here :)

**Comment by voremargot** [comment]
@BooleanJulien your changes look great though! They ran really nicely with my function!

**Comment by BooleanJulien** [comment]
Looks great ty!

**Pull request merged**
